# Generated by Django 4.2.4 on 2023-08-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discount',
        ),
    ]
