# Generated by Django 4.2.4 on 2023-08-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_remove_item_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount',
            field=models.PositiveIntegerField(default=0, help_text='Discount percentage'),
        ),
    ]
