# Generated by Django 4.2.4 on 2023-08-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_item_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_amount',
            field=models.FloatField(default=0, help_text='Discount amount in your currency'),
        ),
    ]
