# Generated by Django 4.2.4 on 2023-08-22 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_item_discount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discount_amount',
        ),
    ]
