# Generated by Django 4.2.4 on 2023-08-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_delete_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='replies',
            field=models.ManyToManyField(to='item.review'),
        ),
    ]
